name: nkisa-ctf

services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: gzctf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql
    healthcheck:
      test: [CMD, pg_isready, -h, 127.0.0.1, -U, postgres, -d, gzctf]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  gzctf:
    image: registry.cn-shanghai.aliyuncs.com/gztime/gzctf:v1.8.7
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      GZCTF_ADMIN_PASSWORD: ${GZCTF_ADMIN_PASSWORD}
      LC_ALL: zh_CN.UTF-8
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./data/files:/app/files
      - ./appsettings.json:/app/appsettings.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
